console.log(1+1);
console.log(2-1);
var x=3*2;
console.log(x);
console.log(parseInt(7/2));
console.log(7/2);
console.log('---------');
console.log(x++);
console.log(++x);
console.log(--x);
console.log(x--);
console.log(x);
console.log('-----------');
console.log(10**4);